### ISSUE TITLE
/opt/bin/unverified-email-api: line 1: syntax error: unexpected "("

### ISSUE THREAD

**Issue by tdjsnelling** [ptek/api.unverified.email#2]
Trying to get this set up locally to play with; I've run

* `./do build`
* `./do dist`
* `./do containers`

The smtpd container starts fine but trying to start the API container with
```docker run --publish 8080:8080 unverified.email/api:8b15a5c7752a0ffe4abf6c974e1a183b80af4fc0```
gives the above error.

**Comment by ptek** [comment]
Could it be, that you are running `./do build` on a macOS and it produces a darwin binary? If so, it is probably getting copied into the container and then can not be run in a linux environment. Could you run the docker command with `-ti` switch? There might be more output to it...

**Comment by ptek** [comment]
Maybe the `./do` script should recognize on which platform it is being run. 
On the other hand, running GHC in a docker container for development could be a performance issue. 
I guess the best way could be detecting the platform only on the dist step, and always preparing a linux binary for it so it can be properly used for a container...

**Comment by tdjsnelling** [comment]
Yeah that'll be it -- I assumed a Linux binary would be built for use in the container. I'm not too familiar with Haskell so I'm not sure how compiling for different targets works, other than that I guess building within the container is an option, but as you said likely a performance issue.

**Comment by ptek** [comment]
I will try to redo and simplify the dist process then so its easier to pick up on different platforms. Maybe not Windows as I have no way of testing it...

**Comment by ptek** [comment]
Just pushed an update to the `./do dist` script. Please try it out...

**Comment by tdjsnelling** [comment]
I had to increase the default RAM limit for docker, but after doing that the build worked fine 👍
